### ISSUE TITLE
GridView doesn't work properly with DatatTable.

### ISSUE THREAD

**Issue by TPIvan** [FritzAndFriends/BlazorWebFormsComponents#160]
_Webforms_ `GridView `  `Datasource ` property type is `object `so it can handle a _collection_ as well as `DataTable`. _Blazor_ `GridView ` `DataSource ` property type is `ienumerable`. To overcome this limitation I have used `.AsEnumerable` extension method. But even though columns auto-generation doesn't work (`AmbiguousMatchException`).  I have also attempted to use `.DefaultView.Cast<DataRowView>()`, but result was the same.
`BoundField `is able to bind to `DataRow `properties (e.g. `RowState `- not very useful), but not to the table columns. Only working scenario I have managed to find was `TemplateField `with content like  `@item[1]`.
 
Full testing code:

    @page "/Bugtest2"
    <h3>Bugtest2</h3>
    <GridView DataSource="myTable.AsEnumerable()" AutogenerateColumns="true">
        <Columns>
            @*<BoundField DataField="col1" HeaderText="Header" />*@
            <BoundField DataField="RowState" HeaderText="Header" />
            <TemplateField HeaderText="Muj sloupec">
                <ItemTemplate Context="item">
                    @item[1]
                </ItemTemplate>
            </TemplateField>
        </Columns>
    
    </GridView>
    @code {
        DataTable myTable;
        protected override void OnInitialized()
        {
            base.OnInitialized();
            myTable = new DataTable();
            myTable.Columns.Add("col1", typeof(string));
            myTable.Columns.Add("col2", typeof(string));
            myTable.Rows.Add("a1", "bb");
            myTable.Rows.Add("a2", "cc");
        }
    }

Full error list for `AutogenerateColumns="true"`

    System.Reflection.AmbiguousMatchException: Ambiguous match found.
       at System.RuntimeType.GetPropertyImpl(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
       at System.Type.GetProperty(String name, BindingFlags bindingAttr)
       at BlazorWebFormsComponents.GridViewRow.BuildRenderTree(RenderTreeBuilder __builder)
       at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
       at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
       at Microsoft.AspNetCore.Components.CascadingValue`1.Render(RenderTreeBuilder builder)
       at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
       at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
       at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
       at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
       at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
       at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
       at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
       at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
       at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
       at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
       at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasks(Task task)
       at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
       at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
       at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.CreateInitialRenderAsync(Type componentType, ParameterView initialParameters)
       at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.RenderComponentAsync(Type componentType, ParameterView initialParameters)
       at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c__11`1.<<InvokeAsync>b__11_0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.AspNetCore.Mvc.ViewFeatures.StaticComponentRenderer.PrerenderComponentAsync(ParameterView parameters, HttpContext httpContext, Type componentType)
       at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.PrerenderedServerComponentAsync(HttpContext context, ServerComponentInvocationSequence invocationId, Type type, ParameterView parametersCollection)
       at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.RenderComponentAsync(ViewContext viewContext, Type componentType, RenderMode renderMode, Object parameters)
       at Microsoft.AspNetCore.Mvc.TagHelpers.ComponentTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
       at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
       at BlazorWebFormsComponents_Test.Pages.Pages__Host.<ExecuteAsync>b__14_1() in C:\MyDiskArea\LiveProgProjects\IVAN_TEST\TechnologyTesting\Blazor\3rdPartyLibraries\BlazorWebFormsComponents_Test\Pages\_Host.cshtml:line 20
       at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
       at BlazorWebFormsComponents_Test.Pages.Pages__Host.ExecuteAsync() in C:\MyDiskArea\LiveProgProjects\IVAN_TEST\TechnologyTesting\Blazor\3rdPartyLibraries\BlazorWebFormsComponents_Test\Pages\_Host.cshtml:line 5
       at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
       at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
       at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
       at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
       at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
       at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
       at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

When  `AutogenerateColumns="false"` the code works and when `<BoundField DataField="col1" ...` is uncommented the error is as follows:

    System.NullReferenceException: Object reference not set to an instance of an object.
       at BlazorWebFormsComponents.GridViewRow.BuildRenderTree(RenderTreeBuilder __builder)
       at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
       at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
       at Microsoft.AspNetCore.Components.CascadingValue`1.Render(RenderTreeBuilder builder)
       at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
       at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
       at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
       at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
       at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
       at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
       at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
       at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
       at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
       at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
       at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasks(Task task)
       at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
       at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
       at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.CreateInitialRenderAsync(Type componentType, ParameterView initialParameters)
       at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.RenderComponentAsync(Type componentType, ParameterView initialParameters)
       at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c__11`1.<<InvokeAsync>b__11_0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.AspNetCore.Mvc.ViewFeatures.StaticComponentRenderer.PrerenderComponentAsync(ParameterView parameters, HttpContext httpContext, Type componentType)
       at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.PrerenderedServerComponentAsync(HttpContext context, ServerComponentInvocationSequence invocationId, Type type, ParameterView parametersCollection)
       at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.RenderComponentAsync(ViewContext viewContext, Type componentType, RenderMode renderMode, Object parameters)
       at Microsoft.AspNetCore.Mvc.TagHelpers.ComponentTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
       at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
       at BlazorWebFormsComponents_Test.Pages.Pages__Host.<ExecuteAsync>b__14_1() in C:\MyDiskArea\LiveProgProjects\IVAN_TEST\TechnologyTesting\Blazor\3rdPartyLibraries\BlazorWebFormsComponents_Test\Pages\_Host.cshtml:line 20
       at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
       at BlazorWebFormsComponents_Test.Pages.Pages__Host.ExecuteAsync() in C:\MyDiskArea\LiveProgProjects\IVAN_TEST\TechnologyTesting\Blazor\3rdPartyLibraries\BlazorWebFormsComponents_Test\Pages\_Host.cshtml:line 5
       at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
       at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
       at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
       at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
       at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
       at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
       at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by grleachman** [comment]
Hi, thank you for reporting this.
At the moment the project owner has explicitly excluded support for DataSource.

see the [readme line 61 ](https://github.com/FritzAndFriends/BlazorWebFormsComponents/blame/dev/README.md#L61) 

We will NOT be converting any DataSource objects, Wizard components, skins or themes.
Regards
Gareth

**Comment by csharpfritz** [comment]
I'm going to turn this into a unit test and we'll get this worked out.

Thank you for trying the GridView....  there's a bit of work due on it, and this makes it easier for us to identify a user case that we overlooked

**Comment by csharpfritz** [comment]
Working on this with a unit test in the fix_GridViewSupportDataTable_160 branch

**Comment by hishamco** [comment]
I planned to work one this, but while you already started it's in your plate ;)

**Comment by hishamco** [comment]
Shall I work on top of your branch or create a new one?

**Comment by csharpfritz** [comment]
That branch has the test built for this feature.  It would be easier to
start there


Jeff

**Comment by hishamco** [comment]
Ok

**Comment by hishamco** [comment]
FYI

After a lot of investigation seems `DataTable` is not supported by default, and the reason of `AmbiguousMatchException` was `DataRow` has multiple versions of indexer which causes the exception when we try to get the value of the `Item` property

Hence, supporting `DataTable` will be tricky little bit and we need to made a special case for it to make work, I will struggle to provide an elegant solution to fix it

**Comment by csharpfritz** [comment]
Right! So we need to re-route the DataTable and DataRow types to some that can be IEnumerable.  I started work on some shim objects in that branch, DataTable and DataRow that could behave that way and wrap a System.Data.DataTable object.  



Jeff

**Comment by hishamco** [comment]
No worry, let me show you what I come up with ...

**Comment by hishamco** [comment]
FYI @TPIvan, I just tested `AsEnumerable()` on ASP.NET GridView and it shows RowError and HasErrors columns, so I tried another way to support `DataTable` while the `DataSource` accepts `IEnumerable<T>` not an `object` as ASP.NET GridView
